[feat/week3] compose
NOW-SOPT-ANDROID/dongmin-park pull request #11
Opened 2024-05-02 08:36 UTC by chattymin

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- close #10 
 
## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- api 연결 했습니다.
- 상황에 맞게 retrofit 3개 생성했어요
- paging 사용했습니다
- LoadingState에 따라 리스트 하단에 CircleProgress or HorizontalDivider를 넣었습니다
- 화면 크기에 따라 grid를 조정해봤어요
- 화면 크기를 activity에서 구하고 composition local로 넘겨줬습니담

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
phone

https://github.com/NOW-SOPT-ANDROID/dongmin-park/assets/52882799/10fef23e-6d91-49de-9e03-a564212e2fc2

tablet

https://github.com/NOW-SOPT-ANDROID/dongmin-park/assets/52882799/e83479cb-e746-4295-9dc0-2a9a2c3c2542

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
- 열심히 해봤어요
- 페이징 처음 적용해봐서 이게 맞는지 잘 모르겠네요...

2024-05-03 14:45 UTC, l2hyunwoo requested changes
흠....조금 더 고민해봐야할 부분이 많은 것 같습니다. 고생많으셨어요.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/build.gradle
```kotlin
implementation("androidx.core:core-ktx:1.13.0")
```

Groovy 기반의 gradle에서는 

```groovy
implementation 'androidx.core:core-ktx:1.13.0'
```

쪽이 좀 더 적확할 것 같습니다.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/remote/dto/response/reqres/Data.kt
Data라는 이름은 어떤 데이터 형식을 명확하게 표현하지 못합니다. 아마 그 플러그인 사용하시는 것 같은데 웬만하면 inner class model 옵션 키고 만드시는 걸 권장드립니다.

<img width="416" alt="스크린샷 2024-05-03 오후 11 20 53" src="https://github.com/NOW-SOPT-ANDROID/dongmin-park/assets/54518925/5476f848-bc73-402c-8720-c887c1043f8a">

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/remote/repositoryImpl/AuthRepositoryImpl.kt
> +                it.headers()[HEADER]
``it.headers()[HEADER]``가 null일 수도 있는데, UI 쪽에서 null을 받는다면 이게 정상응답인지, 에러인지 어떻게 파악할 수 있을까요? 에러 핸들링을 할 때 명확하게 정상동작/에러 케이스를 구분해야 어려운 로직들도 더 쉽게 구현해나갈수 있습니다.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/remote/repositoryImpl/AuthRepositoryImpl.kt
> +                it.headers()[HEADER]
+ 여기서 fold를 사용하시는 이유가 따로 있을까요?

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/data/remote/repositoryImpl/ReqresRepositoryImpl.kt
> +}
이게 응답값은 DTO가 아닌 우리가 흔히 말하는 도메인 객체라고 보여집니다. 여기서 Response라는 것이 User를 표현해주는 것과 어떠한 연관이 있을까요?

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +    }
이와 같이 구현하면 릴리즈 배포 앱에서도 로그 찍힙니다.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +            }
이와 같이 구현을 한 이유가 있을까요? 4라는 숫자가 어떤 역할을 하는지도 명시가 안되어있어서 어떻게 동작하는지 이해가 안됩니다.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/domain/entity/request/RequestSignInEntity.kt
> +)
디버그에서는 동작할 수 있을지도 모르겠지만, 릴리즈에서 난독화 되면 해당 프로퍼티도 난독화될 수 있기 때문에 @SerialName은 꼭 넣어주세요.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/domain/entity/response/ResponseUserList.kt
> +        val last_name: String,
네이밍 컨벤션 (snake_case to camelCase)

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/domain/repository/AuthRepository.kt
> +}
로그인과 회원가입의 결과값이 String이다.... String이 어떤 의미를 나타내는지 이 명세만으로는 잘 이해가 안됩니다. 잘 설계된 함수의 경우(물론 인풋, 아웃풋이 많이 들어가야 하는 함수에는 예외일 수 있겠지만)에는 명세만 보고도 대략적으로 어떤 데이터들이 흘러가는지 파악이 되어야 합니다.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeRoute.kt
> +        PhoneSize.BIG -> 3
굳이 hoisting 할 필요가 있을까요?

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeRoute.kt
> +                    }
이것들도 parent에서 제공해주는 Modifier를 사용해야하는 이유가 있나요?

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeState.kt
> +    var loadState: UiState<Unit> = UiState.Loading,
이렇게 바꾸면, HomeState를 사용하는 이유가 있을까요?

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeViewModel.kt
> +    private val setState: (UiState<Unit>) -> Unit,
- setState를 패러미터로 받아와야 하는 이유를 모르겠습니다.
- PagingSource는 DataLayer인데 UI의 로직까지 건드려야 하는 이유도 모르겠네요.
- Paging3가 궁극적으로 지향하는 것은 아마 사용해보면서 더 느껴볼 수 있겠지만, PagingSource가 알아서 데이터 준비할테니까 Pager 그냥 사용해서 UI 데이터만 잘 보여줘~에요 (물론 배너 광고 같은거 추가되면 좀 달라지지만). 지금의 로직은 UI에 데이터를 보여주기 위해서 UI에서 데이터를 일부러 건드리는 것 같은 느낌을 들게 하는 코드가 들어있어서 수정이 요구됩니다.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/main/MainActivity.kt
> +        fun getPhoneSize(phoneWidth: Int): PhoneSize = when {
```suggestion
        fun of(deviceWidth: Int): PhoneSize = when {
```

안드로이드는 핸드폰뿐만 아니라 다른 기기도 지원하니 그에 맞춰서 수정해주는게 좋을 것 같네요.

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/my/MySideEffect.kt
> +    data class SnackBar(val message: Int) : MySideEffect()
```suggestion
    data class SnackBar(@StringRes val message: Int) : MySideEffect()
```

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/my/MyViewModel.kt
> +    private val userDataStore: UserDataStore,
Repository를 참조하고 있는데 굳이 DataStore까지 참조하는 이유가 있나요?

2024-05-03 14:45 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/signup/SignUpViewModel.kt
> +            else -> R.string.server_error
각각의 에러케이스가 어떤 에러인지 명확하게 보여지지 못하는 것 같습니다. 어떻게하면 더 에러를 명확하게 표현할 수 있을까요?

2024-05-03 14:45 UTC, l2hyunwoo commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.20' apply false
버전호환 잘되나요?

2024-05-03 15:55 UTC, chattymin commented on app/build.gradle
습관적으로 Kotln DSL처럼 해버렸네요! Groovy스럽게 수정하겠습니당 :)

2024-05-03 16:09 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/data/remote/dto/response/reqres/Data.kt
이건 모르고 있던 기능이네요..!!
바로 적용 하겠습니다!

그리고 기존에 만들어뒀던 클래스는 inner class로 수정해두겠습니당

2024-05-05 13:00 UTC, boiledEgg-s approved these changes
너무 잘짜인 코드에 1차 놀라고, 그럼에도 22개나 달린 리뷰에 2차 놀랍니다,,
이번주엔 과제도 딱히 없으니 이 코드 분석을 제대로 해봐야겠네요~

2024-05-05 13:00 UTC, boiledeggg commented on app/src/main/java/com/sopt/now/compose/data/local/UserDataStoreImpl.kt
> +        set(value) = dataStore.edit { putString(USER_ID, value) }
이 코드는 다음 기능을 하는 게 맞나요??
- `get()`으로 변수를 불러올 때 Preference로부터 데이터를 불러오는 것
- `set()`으로 해당 변수에 값을 재할당하면 Preference에도 넣을 것

2024-05-05 13:39 UTC, youjin09222 approved these changes
와 진짜 클래스가 다르네요.. 매번 놀랍니다😲
이번 주차도 열심히 코드 분석해야겠어요🧐

2024-05-05 13:40 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/di/HeaderInterceptor.kt
> +    }
이렇게 Dagger로 의존성을 주입하면 테스트 용이성과 코드 유지보수성을 높일 수 있군요!! 
코드가 간결하고 가독성이 높네요! 저도 적용해보겠습니다!

2024-05-05 13:56 UTC, youjin09222 commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +        .build()
@HEADER, @AUTH는 직접 정의하신 어노테이션인가요??

2024-05-05 14:57 UTC, hyeumm approved these changes
역시 OB시네요.. 항상 새로운 내용을 많이 알아가는 것 같아요!
매주매주 다양한 내용들을 많이 배울 수 있어서 좋았어요! 이번 과제도 수고많으셨습니닷 :-)

2024-05-05 14:57 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +                Timber.tag("okhttp").d(JSONObject(message).toString(4))
timber를 새로 봐서 무엇인지 궁금했는데 개발 중에는 로그를 출력하고 릴리즈에는 로그를 출력하지 않는 기능이군요..! 신기하네요!

2024-05-06 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/data/local/UserDataStoreImpl.kt
> +        set(value) = dataStore.edit { putString(USER_ID, value) }
넵넵 맞습니다!

2024-05-06 04:28 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/di/HeaderInterceptor.kt
> +    }
정확히는 Dagger에서 다음단계로 발전한 Hilt를 사용하고 있습니당 :)

2024-05-06 04:31 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +        .build()
넵 맞습니다!

같은 타입을 리턴하는게 하나만 있다면 자동으로 Hilt가 연결해주지만, 두개 이상 있다면 어떤 친구를 연결해줘야하는지 오류가 나게 됩니다. 그래서 Custom Anotation을 사용해서 얘는 얘랑 연결되는거야~ 하고 알려주고 있는 과정입니답!
눈썰미 최고네요...!!!

2024-05-06 04:32 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +                Timber.tag("okhttp").d(JSONObject(message).toString(4))
Timber도 추가작업을 하지 않는다면 릴리즈시에도 로그가 나오게 됩니다...!!
조금 더 간단한 log라고 생각해주시면 돼용~

2024-05-07 04:49 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +                Timber.tag("okhttp").d(JSONObject(message).toString(4))
앗 무조건 그런건 아니군요! 설명 감사합니다 :)

2024-05-07 05:49 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/domain/entity/request/RequestSignInEntity.kt
> +)
이부분은 몰랐던 부분이네요! 
없어도 이름이 같다면 정상적으로 동작하기 때문에 불필요한 행동이 아닐까 라는 생각에 이번에 지워봤었는데 덕분에 이유를 알고 @SerialName을 사용할 수 있게 되었습니다! 감사합니다:)

2024-05-07 05:57 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeRoute.kt
> +        PhoneSize.BIG -> 3
굳이 그럴 필요가 없을 것 같네요.
습관적으로 hoisting했던 것 같습니다

오히려 hoisting한 것 때문에 가독성이 좀 떨어지는 느낌이 있네요 감사합니다!

2024-05-07 05:57 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeRoute.kt
> +                    }
이것도 그래야할 이유가 없네요...
앞으론 조금 더 생각해보고 사용하도록 하겠습니담

2024-05-07 11:49 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +    }
```
@HiltAndroidApp
class App : Application() {
    override fun onCreate() {
        super.onCreate()

        initTimber()
    }

    private fun initTimber() {
        if (BuildConfig.DEBUG) Timber.plant(Timber.DebugTree())
    }
}
```

 저는 이렇게 Appplication에서 선언해서 사용했는데 level에서 
`if (BuildConfig.DEBUG) ` 을 이용해서 나타내는것과 어떤 차이가 있나요??
@l2hyunwoo

2024-05-07 12:04 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +            }
log로 json과 관련된 내용이 나올 때 보기 편하게 하기 위한 장치입니다! json인지 판단하여 tab(4 space)를 주는 코드입니다.
다른 사람이 작성한 코드에서 가져와 사용하다보니 의미를 생각하지 않고 늘 쓰던대로 사용한 것 같습니다. 

4 라는 숫자보다는 "TAB" 혹은 "ONE_TAB"이라는 상수로 표현하도록 하겠습니다. 뭔가 아쉬워서 좀 더 고민해보고 상수명 짓도록 하겠습니다 :)

2024-05-07 14:04 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeState.kt
> +    var loadState: UiState<Unit> = UiState.Loading,
전혀 없어졌습니다..!!
paging을 사용하니 굳이 넣을 필요가 없어져서 그냥 paging관련 state로 화면을 나타냈습니다

감사합니다 :)

2024-05-07 14:20 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeViewModel.kt
> +    private val setState: (UiState<Unit>) -> Unit,
이 부분은 제가 Paging에 대한 이해도가 부족해서 이렇게 된 것 같습니다. 
말씀해주신대로 DataLayer라는 역할에 맞도록 수정해봤습니담...

제대로 사용하기는 좀 어려운거 같은데 감은 좀 잡은 것 같습니다...!!
감사합니다 :)

2024-05-07 14:33 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/data/remote/repositoryImpl/ReqresRepositoryImpl.kt
> +}
이 부분은 제가 네이밍을 할 때 잘 못한 부분 같습니다. 
실수로 해당 이름을 사용한 것 같네요.

보다 명확한 이름인 `ReqresUserModel`로 수정했습니다!!

2024-05-07 15:18 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeViewModel.kt
> +    private val setState: (UiState<Unit>) -> Unit,
저도 수정하고 나니 MutableStateFlow로 저장해서 사용하는 방식이었습니다. 하지만, 상욱님에게 남김 코드리뷰를 보니 왜 MutableStateFlow여야하냐는 내용이 있어 생각해봤습니다. 
그래서 결론은 Repository에서 Pager를 flow로 이미 주고있는데 그걸 굳이 형변환 시킬 이유가 없다는 생각에 flow로 저장하는 로직을 사용해봤습니다. 

```
@HiltViewModel
class HomeViewModel @Inject constructor(
    reqresRepository: ReqresRepository,
) : ViewModel() {
    val userListStream: Flow<PagingData<ReqresUserModel>> =
        reqresRepository.getUserList().distinctUntilChanged().cachedIn(viewModelScope)
}
```
그후 아래와 같이 UI에서 사용하고 있습니다. 
```
@Composable
fun HomeRoute(
    modifier: Modifier,
    viewModel: HomeViewModel = hiltViewModel(),
) {
    val userPagingItems = viewModel.userListStream.collectAsLazyPagingItems()

    HomeScreen(
        userList = userPagingItems,
        modifier = modifier
    )
}
```


이 코드를 구현하며 'Flow는 데이터를 emit하거나 collect하는 것으로만 알고있었는데 어떻게 데이터를 저장해서 UI에 나타내주는 거지?'라는 의문점이 생겼습니다. 제 생각으로는 viewModel에서 data를 가져와 바로 방출하고, UI(Compose)에서 받아와 collectAsLazyPagingItems()로 저장해서 사용하는 방식이다는 결론을 내렸습니다

즉, MutableStateFlow를 사용할때는 저장소가 viewModel에 하나, UI에 하나였다면 Flow를 사용하면 viewModel에서는 받아와서 넘겨주는 역할만 하고 UI에 저장하는 단일 저장소 방식이 되었다고 생각하는데 맞는걸까요??

2024-05-07 16:24 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/feature/my/MyViewModel.kt
> +    private val userDataStore: UserDataStore,
Repository에서 DataStore를 연결시켜 작업해야하는데 예전에 둘다 불러오던 습관때문에 둘다 연결했습니다...!!
다른 ViewModel에서도 같은 코드를 적어둔게 보여 수정하도록 하겠습니다. 

그런데 해당 viewModel에서는 UI상으로 호출 자체를 안해도 될 것 같아 호출하지 않도록 수정했습니다 :)

2024-05-07 17:11 UTC, chattymin commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.20' apply false
버전호환이 어떤걸 말씀하시는지 모르겠는데 정상 작동됩니답...!
최신버전인 "1.9.24"를 넣으니 오히려 에러가 나서 그냥 놔뒀습니다

수정해야하는 사항이라면 추가적으로 말씀해주시면 감사하겠습니다 :)

2024-05-07 17:38 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/domain/repository/AuthRepository.kt
> +}
너무나 맞는 말입니다.
성공하면 헤더를 반환 후 DataStore에 넣어야 한다는 생각에 매몰돼서 이러한 코드를 작성한 것 같습니다.

데이터를 가공 후 viewModel에 넘겨주는 방식을 써보자는 생각에 그걸 생각을 못했던 것 같습니다.
심지어 가공을 Data Layer에서 하려고 했으니 차라리 Domain에서 UseCase를 만들어서 했다면 나았을 것 같네요.

우선은 Result를 반환하는 형식으로 수정부터 한 후, useCase도 적용해보도록 하겠습니다 :)

2024-05-07 17:41 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/data/remote/repositoryImpl/AuthRepositoryImpl.kt
> +                it.headers()[HEADER]
정상응답일 경우 .orEmpty를 사용하여 정상적인 header가 들어가거나, empty가 들어가게 설정했습니다. 
그렇다면 로그를 통해 세가지 경우로 추론이 가능할 것이라 생각됩니다.
1. 정상 값 -> 문제없음
2. 빈값(empty) -> 성공했지만, null이었음 -> header 추출과정의 오류
3. null -> 통신 자체가 실패

이렇게 판단 할 수 있을 것 같습니다. 물론 아래에 코드리뷰 달아주신 것 처럼 String?을 SignUp에서 반환한다는 것 자체가 이상해서 수정하긴 했습니다 :)

2024-05-07 17:42 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/data/remote/repositoryImpl/AuthRepositoryImpl.kt
> +                it.headers()[HEADER]
fold의 경우 데이터를 가공하여 viewModel로 넘겨주어 viewModel의 역할을 줄이고 가볍게 하고싶다는 생각에 데이터를 가공하여 return하고자 사용했습니다. 하지만 코드를 수정하며 생각해보니 데이터 가공을 data레이어에서 시도한게 이상한 것 같네요. 수정하여 useCase에서 해보도록 하겠습니다 :)

2024-05-08 05:27 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +            }
TAB, UNIT_TAB 정도가 좋을 것 같네요. 코드에서 기저가 되는 값들은 ONE 보단 UNIT을 많이 사용하는 것 같아요.

2024-05-08 05:28 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/domain/repository/AuthRepository.kt
> +}
- UseCase가 필수적일까요? 왜 UseCase 레이어를 추가로 두어야할까요?
- 추가리뷰) AuthRepository의 함수 이름이 너무 서버 환경에 의존적인 것 같습니다. post~(remote), insrert~(local DB) 이런 네이밍보단 앱 내 로직에 친화적인 네이밍으로 데이터 소스에 의존적이지 않은 방향으로 코드를 작성하면 좋을 것 같습니다.

2024-05-08 05:34 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeViewModel.kt
> +    private val setState: (UiState<Unit>) -> Unit,
Pager에서 PagingData를 전달하는 Flow를 반환합니다. 즉, 이미 데이터를 발행하고 있는 곳은 PagingSource이구요 저희는 그냥 그 페이징 데이터를 사용만 하면 되는겁니다. 그래서 데이터를 발행해주는 곳을 추가로 둘 필요가 없다는 의도에서 리뷰를 남긴거긴 합니다. 동민님이 생각하신 방향이 맞습니다.

참고 - [AndroidX Jetpack ~ Paging 데이터의 위치 살펴보기](https://pluu.github.io/blog/android/2022/01/02/paging/)

2024-05-08 05:35 UTC, l2hyunwoo commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.20' apply false
아직 plugin serialization은 1.9.23만 나오긴 했습니다

2024-05-08 05:35 UTC, l2hyunwoo commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.20' apply false
그런데 굳이 수정할 필요는 없습니다. 정상동작 된다면요

2024-05-08 05:36 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/feature/home/HomeState.kt
> +    var loadState: UiState<Unit> = UiState.Loading,
불필요한 코드면 삭제 처리해주세요.

2024-05-08 05:37 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/now/compose/di/NetModule.kt
> +    }
아하 지금 Timber가 디버그에서만 찍히는 군요. 이 컨텍스트 까먹고 리뷰했습니다. 그대로 두셔도 될 것 같아요.

2024-05-08 16:55 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/domain/repository/AuthRepository.kt
> +}
UseCase는 필수적이지는 않다고 생각합니다.
제가 UseCase를 쓰고자 했던 이유는 정보를 추가적으로 가공할 필요가 있다고 생각했고, 해당 과정을 viewModel에서 하는 것 보다는 UseCase에서 하는게 좋지 않을까 라는 생각을 가지고 있었습니다. 하지만 현재 생각해보니 UseCase에 대해서 잘 모르고, 그저 남들 하는거라 해볼까 했던 생각이었어서 좀 더 공부해보고 그때도 필요하다고 생각된다면 그 때 적용하도록 하겠습니다!

그리고 useCase를 통해서 Header를 추출한다면 함수이름이 `getHeader`와 같이 적을 것 같은데 그러면 오히려 viewModel에서 `getHeader`를 호출하면 SignIn이 실행되는.... 기이한 현상이 일어날 것 같네요. 현재 상황에서는 UseCase는 불필요한 것 같습니다!!

2024-05-08 17:01 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/domain/repository/AuthRepository.kt
> +}
AuthRepository는 Domain에 속하는 친구고, local에서 받아오는지 remote에서 받아오는지는 DataStore와 DataSource에서 받아오는지에서 정해지는거니까 Repository는 해당 사항을 몰라도 될 것 같습니다.

또한 현재는 Remote이지만 local로 바뀔 수도 있고, 앞서 말했던 것 처럼 Repository가 서버에 대한 종속성을 가지면 안될 것 같습니다. 

그래서 아래와 같이 수정했습니다 :)
postSignUp -> registerUser
postSignIn -> verifyUser

그런데 그냥 post, insert를 뺀 signUp, signIn으로 써도 되는걸까요??
위와같이 작성하니 의존성은 없는 이름이 되었지만 이해하기 어려운 이름이 된 것 같은 느낌입니다...

2024-05-17 03:22 UTC, l2hyunwoo approved these changes
다음 PR때 수정해서 반영하시면 될 것 같습니다.

2024-05-20 16:44 UTC, merged